# Generated by Django 4.1.4 on 2023-08-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_bba_first_subject_12th_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mba',
            name='rollno_ug',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mba',
            name='year_of_ug',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mbatemp',
            name='rollno_ug',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mbatemp',
            name='year_of_ug',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
