# Generated by Django 4.1.4 on 2023-08-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_mba_rollno_ug_alter_mba_year_of_ug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
